name: Generated CI/CD Pipeline
'on':
  push:
    branches:
    - main
jobs:
  lint:
    uses: .github/workflows/python.yml
    with:
      job: lint
  test:
    uses: .github/workflows/python.yml
    with:
      job: test
  package:
    uses: .github/workflows/python.yml
    with:
      job: package
  deploy:
    uses: .github/workflows/deploy-docker.yml
